-- MySQL Script generated by MySQL Workbench
-- Wed Jan 10 15:32:18 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema gruppinlamning_relationModel
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gruppinlamning_relationModel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gruppinlamning_relationModel` DEFAULT CHARACTER SET utf8 ;
USE `gruppinlamning_relationModel` ;

-- -----------------------------------------------------
-- Table `gruppinlamning_relationModel`.`Leverantor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gruppinlamning_relationModel`.`Leverantor` (
  `id_OrganisationsNummer` INT NOT NULL,
  `telefonNummer` VARCHAR(45) NOT NULL,
  `namn` VARCHAR(45) NOT NULL,
  `mailAdress` VARCHAR(45) NOT NULL,
  `provisionProcent` DOUBLE NOT NULL,
  PRIMARY KEY (`id_OrganisationsNummer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gruppinlamning_relationModel`.`Produkt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gruppinlamning_relationModel`.`Produkt` (
  `ID_ArtNr` INT NOT NULL AUTO_INCREMENT,
  `produktNamn` VARCHAR(45) NOT NULL,
  `Kategori` VARCHAR(45) NOT NULL,
  `Leverantor_id_OrganisationsNummer` INT NOT NULL,
  PRIMARY KEY (`ID_ArtNr`, `Leverantor_id_OrganisationsNummer`),
  INDEX `fk_Produkt_Leverantor_idx` (`Leverantor_id_OrganisationsNummer` ASC),
  CONSTRAINT `fk_Produkt_Leverantor`
    FOREIGN KEY (`Leverantor_id_OrganisationsNummer`)
    REFERENCES `gruppinlamning_relationModel`.`Leverantor` (`id_OrganisationsNummer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gruppinlamning_relationModel`.`aktiv_auktion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gruppinlamning_relationModel`.`aktiv_auktion` (
  `id_auktionsnummer` INT NOT NULL AUTO_INCREMENT,
  `startDatum` DATETIME NOT NULL,
  `slutDatum` DATETIME NOT NULL,
  `utropsPris` INT NOT NULL,
  `slutPris` INT NULL,
  `acceptPris` INT NULL,
  `Produkt_ID_ArtNr` INT NOT NULL,
  PRIMARY KEY (`id_auktionsnummer`, `Produkt_ID_ArtNr`),
  INDEX `fk_aktiv_auktion_Produkt1_idx` (`Produkt_ID_ArtNr` ASC),
  CONSTRAINT `fk_aktiv_auktion_Produkt1`
    FOREIGN KEY (`Produkt_ID_ArtNr`)
    REFERENCES `gruppinlamning_relationModel`.`Produkt` (`ID_ArtNr`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gruppinlamning_relationModel`.`Kund`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gruppinlamning_relationModel`.`Kund` (
  `id_Kundnummer` INT NOT NULL AUTO_INCREMENT,
  `namn` VARCHAR(45) NOT NULL,
  `telnr` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Kundnummer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gruppinlamning_relationModel`.`Bud`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gruppinlamning_relationModel`.`Bud` (
  `id_Bud` INT NOT NULL AUTO_INCREMENT,
  `currentBid` INT NOT NULL,
  `tidPunkt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `aktiv_auktion_id_auktionsnummer` INT NOT NULL,
  `Kund_id_Kundnummer` INT NOT NULL,
  PRIMARY KEY (`id_Bud`, `aktiv_auktion_id_auktionsnummer`, `Kund_id_Kundnummer`),
  INDEX `fk_Bud_aktiv_auktion1_idx` (`aktiv_auktion_id_auktionsnummer` ASC),
  INDEX `fk_Bud_Kund1_idx` (`Kund_id_Kundnummer` ASC),
  CONSTRAINT `fk_Bud_aktiv_auktion1`
    FOREIGN KEY (`aktiv_auktion_id_auktionsnummer`)
    REFERENCES `gruppinlamning_relationModel`.`aktiv_auktion` (`id_auktionsnummer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Bud_Kund1`
    FOREIGN KEY (`Kund_id_Kundnummer`)
    REFERENCES `gruppinlamning_relationModel`.`Kund` (`id_Kundnummer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gruppinlamning_relationModel`.`auktionsHistorik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gruppinlamning_relationModel`.`auktionsHistorik` (
)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
